PLAYBOOK_ENTRIES = [
    {
        "id": "pb_01",
        "rule_code": "PB-01",
        "title": "Insufficient Funds — Transient Off-Hours Decline",
        "failure_reason": "insufficient_funds",
        "payment_method": "card",
        "trigger": "Decline due to low balance during non-banking hours (nights/weekends).",
        "recommended_action": "schedule_retry",
        "tool_params": {"delayHours": 4, "reason": "Targeting standard morning clearing cycle (09:00 - 11:00 AM)"},
        "rationale": "Liquidity is often replenished during business hours. Retrying 4-6 hours later during banking clearing windows yields a 42% higher capture rate without customer disturbance.",
        "ml_threshold": 0.65
    },
    {
        "id": "pb_02",
        "rule_code": "PB-02",
        "title": "Insufficient Funds — End-of-Month Payday Alignment",
        "failure_reason": "insufficient_funds",
        "payment_method": "card",
        "trigger": "Low balance decline occurring between the 25th and 29th of the month.",
        "recommended_action": "schedule_retry",
        "tool_params": {"delayHours": 48, "reason": "Deferring to 1st of the month salary deposit window"},
        "rationale": "End-of-month cashflow constraints are seasonal. Scheduling the retry for the 1st of the calendar month aligns with salary credit cycles.",
        "ml_threshold": 0.70
    },
    {
        "id": "pb_03",
        "rule_code": "PB-03",
        "title": "Insufficient Funds — Multi-Attempt Exhaustion",
        "failure_reason": "insufficient_funds",
        "payment_method": "card",
        "trigger": "Repeated insufficient funds failure (attempt count >= 3).",
        "recommended_action": "send_recovery_message",
        "tool_params": {"channel": "email", "templateId": "payment_failed_alternative_method"},
        "rationale": "Subsequent automated retries face steep diminishing returns and risk issuer account locks. Switch to customer self-service recovery with alternate payment options (UPI, alternate card).",
        "ml_threshold": 0.60
    },
    {
        "id": "pb_04",
        "rule_code": "PB-04",
        "title": "Card Expired — Direct Retry Suppression & Self-Service Link",
        "failure_reason": "card_expired",
        "payment_method": "card",
        "trigger": "Gateway returns expired credentials or tokenization lifecycle expiry.",
        "recommended_action": "send_recovery_message",
        "tool_params": {"channel": "email", "templateId": "card_expired_update_v1", "customMessage": "Your payment card on file has expired. Update details via this secure 1-click link."},
        "rationale": "Automated retries on an expired card are guaranteed to fail and cause merchant fees. Generating a signed single-use recovery link enables seamless customer credentials update.",
        "ml_threshold": 0.85
    },
    {
        "id": "pb_05",
        "rule_code": "PB-05",
        "title": "Card Expired — High Value VIP Subscription Retention",
        "failure_reason": "card_expired",
        "payment_method": "card",
        "trigger": "Card expired on enterprise / high-tier subscription (> ₹10,000).",
        "recommended_action": "send_recovery_message",
        "tool_params": {"channel": "email", "templateId": "vip_card_renewal_urgent", "priority": "high"},
        "rationale": "High-value subscriptions require immediate zero-churn prevention. Dispatch prioritized recovery message with dedicated account assurance.",
        "ml_threshold": 0.90
    },
    {
        "id": "pb_06",
        "rule_code": "PB-06",
        "title": "Bank Outage — Immediate Automated Re-Capture",
        "failure_reason": "bank_outage",
        "payment_method": "upi",
        "trigger": "Issuing bank switch or payment gateway reports transient 5xx downtime.",
        "recommended_action": "attempt_recovery",
        "tool_params": {"reason": "Transient issuing bank network failure resolved; executing immediate capture."},
        "rationale": "Bank outages are transient network glitches. Once the gateway health status recovers, an immediate retry has an 80%+ immediate recovery rate.",
        "ml_threshold": 0.88
    },
    {
        "id": "pb_07",
        "rule_code": "PB-07",
        "title": "Bank Outage — Core Banking Nightly Maintenance",
        "failure_reason": "bank_outage",
        "payment_method": "netbanking",
        "trigger": "Bank decline during 01:00 AM - 04:00 AM maintenance window.",
        "recommended_action": "schedule_retry",
        "tool_params": {"delayHours": 5, "reason": "Deferred until morning after bank maintenance window closes"},
        "rationale": "Core banking system batch processing takes banks offline during late night hours. Deferring to 06:30 AM avoids repeat declines.",
        "ml_threshold": 0.82
    },
    {
        "id": "pb_08",
        "rule_code": "PB-08",
        "title": "Network Timeout — Gateway Status Inquiry & Capture Retry",
        "failure_reason": "network_timeout",
        "payment_method": "card",
        "trigger": "Gateway or 3DS socket timeout with no debit confirmation.",
        "recommended_action": "attempt_recovery",
        "tool_params": {"reason": "Socket timeout resolved; attempting instant recovery capture."},
        "rationale": "Network timeouts are almost always transient infrastructure jitter. Retrying immediately recovers lost transactions before the user abandons session.",
        "ml_threshold": 0.89
    },
    {
        "id": "pb_09",
        "rule_code": "PB-09",
        "title": "Authentication Failed — 3DS / OTP Friction Link",
        "failure_reason": "authentication_failed",
        "payment_method": "card",
        "trigger": "Customer dropped off during SMS OTP verification or entered wrong OTP.",
        "recommended_action": "send_recovery_message",
        "tool_params": {"channel": "email", "templateId": "3ds_auth_retry_link"},
        "rationale": "Automated retries cannot solve customer authentication challenges. Sending a recovery checkout link allows the user to re-authenticate with biometric or SMS OTP.",
        "ml_threshold": 0.75
    },
    {
        "id": "pb_10",
        "rule_code": "PB-10",
        "title": "High Risk Fraud — Security Quarantine & Human Escalation",
        "failure_reason": "high_risk_fraud",
        "payment_method": "card",
        "trigger": "Transaction triggered fraud velocity, stolen card BIN, or disposable email markers.",
        "recommended_action": "escalate_to_human",
        "tool_params": {"priority": "urgent", "reason": "Anti-fraud security threshold triggered."},
        "rationale": "Zero automated retries permitted on potential fraud cases to prevent chargeback fees and merchant card network fines. Escalate immediately to risk operations.",
        "ml_threshold": 0.05
    },
    {
        "id": "pb_11",
        "rule_code": "PB-11",
        "title": "Subscription Mandate — NACH / e-Mandate Re-Presentation",
        "failure_reason": "subscription_mandate",
        "payment_method": "subscription_mandate",
        "trigger": "Automated recurring standing instruction debit rejected by bank.",
        "recommended_action": "schedule_retry",
        "tool_params": {"delayHours": 24, "reason": "Regulatory 24-hour cooling interval for mandate re-presentation"},
        "rationale": "Standing instruction compliance rules mandate a minimum 24-hour interval between recurring presentation attempts.",
        "ml_threshold": 0.78
    },
    {
        "id": "pb_12",
        "rule_code": "PB-12",
        "title": "Daily Card Limit Exceeded — Next-Day Clearing Retry",
        "failure_reason": "limit_exceeded",
        "payment_method": "card",
        "trigger": "Customer bank daily transaction volume or velocity cap exceeded.",
        "recommended_action": "schedule_retry",
        "tool_params": {"delayHours": 12, "reason": "Scheduled for 00:05 AM next calendar day after bank daily limit reset"},
        "rationale": "Daily banking caps reset at midnight. Rescheduling for the next calendar morning avoids repeated limit rejections.",
        "ml_threshold": 0.84
    },
    {
        "id": "pb_13",
        "rule_code": "PB-13",
        "title": "UPI Intent / VPA Request Timeout",
        "failure_reason": "upi_timeout",
        "payment_method": "upi",
        "trigger": "Customer failed to approve UPI push notification on PhonePe/GPay within 5 minutes.",
        "recommended_action": "send_recovery_message",
        "tool_params": {"channel": "sms", "templateId": "instant_upi_recovery"},
        "rationale": "UPI requests expire rapidly. Dispatching an SMS / WhatsApp recovery link allows instant reopening of the UPI app with pre-filled VPA intent.",
        "ml_threshold": 0.81
    },
    {
        "id": "pb_14",
        "rule_code": "PB-14",
        "title": "High Value Large Enterprise Invoice Policy (> ₹50,000)",
        "failure_reason": "high_value_policy",
        "payment_method": "card",
        "trigger": "Payment amount exceeds automated approval ceiling (> ₹50,000).",
        "recommended_action": "escalate_to_human",
        "tool_params": {"priority": "high", "reason": "High-value transaction exceeds automated autonomy threshold"},
        "rationale": "High-ticket enterprise purchases require human account executive verification before executing retries or customer communication.",
        "ml_threshold": 0.50
    },
    {
        "id": "pb_15",
        "rule_code": "PB-15",
        "title": "Multi-Acquirer Gateway Switch Failover",
        "failure_reason": "bank_outage",
        "payment_method": "card",
        "trigger": "Primary gateway degraded with elevated latency and error spikes.",
        "recommended_action": "attempt_recovery",
        "tool_params": {"reason": "Re-routing transaction to backup payment gateway rail"},
        "rationale": "Switching acquirer rails bypasses localized gateway degradation and rescues checkout conversion in real time.",
        "ml_threshold": 0.86
    },
    {
        "id": "pb_16",
        "rule_code": "PB-16",
        "title": "Cross-Border International Card Rejection",
        "failure_reason": "currency_mismatch",
        "payment_method": "card",
        "trigger": "Non-domestic card rejected due to 3DS / currency restrictions.",
        "recommended_action": "send_recovery_message",
        "tool_params": {"channel": "email", "templateId": "international_checkout_portal"},
        "rationale": "Provide the customer with a localized international payment portal supporting dynamic currency conversion (DCC) and Stripe/PayPal rails.",
        "ml_threshold": 0.77
    }
]
